//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDDService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BattlesharpEntities : DbContext
    {
        public BattlesharpEntities()
            : base("name=BattlesharpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<jugador> jugador { get; set; }
        public DbSet<puntuacion> puntuacion { get; set; }
        public DbSet<mejores> mejores { get; set; }
    }
}
